### ISSUE TITLE
好像有bug？

### ISSUE THREAD

**Issue by RemiTsuma** [b11p/OsuQqBotForNewbieGroup#19]
![Screenshot_2024-09-12-11-12-47-42_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/user-attachments/assets/e8d6f649-343b-4349-97ef-3f0d9ee2bf3c)

**Comment by b11p** [comment]
用“绑定 id”绑定

**Comment by RemiTsuma** [comment]
試過很多次 但機器人沒有回應

**Comment by b11p** [comment]
这个应该是分身，没有绑定权限，你之前的命令绑定的是别的bot。有问题加群563180497
