### ISSUE TITLE
用 ~1 查询ExSPer的taiko信息无任何回应

### ISSUE THREAD

**Issue by Exsper** [b11p/OsuQqBotForNewbieGroup#3]
同时查其他模式、其他玩家均有正确回应

**Comment by b11p** [comment]
![image](https://user-images.githubusercontent.com/35132976/106376237-a78b2f80-63d6-11eb-8ecb-10f0859fac6a.png)
我这暂时是正常的。这个问题一般是腾讯的风控引起的，我只能尽力缓解，没办法解决。如果你有什么补充的话，欢迎回复。
